name: Deploy to Dokku, subtree

on: 
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: dokku/ci-docker-image:latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.DOKKU_SSH_KEY }}
      GIT_REMOTE_URL: ssh://docku@${{ secrets.DOKKU_HOST }}/edm-data-enginering
      app_remote_branch: main
      git_push_flags: --force
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: test/
      - name: Setup
        run: |
          sudo apt install git-core
          /bin/setup-ssh
      - name: Deploy
        run: git push "$GIT_REMOTE_URL" `git subtree split --prefix test` --force

