name: Deploy to Dokku - production

on: 
  workflow_dispatch:

env:
  DOKKU_APP_NAME: 'edm-data-engineering'
  DOKKU_REMOTE_BRANCH: 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        uses: woudsma/dokku-deploy-github-action@v1
        env:
          SQL_ENGINE_EDM_DATA: ${{ secrets.SQL_ENGINE_EDM_DATA }}
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_KEY }}
          dokku-host: ${{ secrets.DOKKU_HOST }}
          app-name: ${{ env.DOKKU_APP_NAME }}
          app-remote-branch: ${{ env.DOKKU_REMOTE_BRANCH }}
          git-push-flags: --force

